🧪📦 Bump `cibuildwheel` to v3.0.1
This is the last version that does not require additional infra
patches.

v3.2.0 hits the following warning on macOS:

```console
  + pip install --upgrade delocate 'build[virtualenv]' -c file:///Users/runner/work/_temp/cibw/lib/python3.13/site-packages/cibuildwheel/resources/constraints-python39.txt
  Collecting delocate
    Downloading delocate-0.13.0-py3-none-any.whl.metadata (15 kB)
  Collecting build[virtualenv]
    Downloading build-1.3.0-py3-none-any.whl.metadata (5.6 kB)
  INFO: pip is looking at multiple versions of delocate to determine which version is compatible with other requirements. This could take a while.
  ERROR: Cannot install delocate==0.13.0 because these package versions have conflicting dependencies.

  The conflict is caused by:
      delocate 0.13.0 depends on packaging>=20.9
      The user requested (constraint) packaging==25.0,==26.0

  To fix this you could try to:
  1. loosen the range of package versions you've specified
  2. remove package versions to allow pip to attempt to solve the dependency conflict

  ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
  ::endgroup::Installing build tools...
```

It also auto-enables Python 3.14t, which fails with
```console
  E   RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module 'pylibsshext._libssh_version', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.
3522
```
in the `pytest` invocation.